<?php
/** @var \Application\View\Renderer\PhpRenderer $this */

$flash = $this->flashMessenger();

echo $flash->render('error',   ['alert', 'alert-dismissible', 'alert-danger']);
echo $flash->render('info',    ['alert', 'alert-dismissible', 'alert-info']);
echo $flash->render('default', ['alert', 'alert-dismissible', 'alert-warning']);
echo $flash->render('success', ['alert', 'alert-dismissible', 'alert-success']);
